In [4]:
import pandas as pd

In [10]:
kagglepath =  "../../dataset/kgdataset.csv"
surveypath = "../../dataset/survey_data.xlsx"
df = pd.read_csv(kagglepath)
df2 = pd.read_excel(surveypath)
df2.drop(df2.columns[0],axis=1, inplace=True)
df2.columns = df.columns
combined = pd.concat([df, df2], ignore_index=True)
combined

,Age,Sleep Hours,Feel Rested,Daily Screen Time,Use Before Sleep,Stress Level,Anxiety/Low Mood,Wellness Apps,Sleep Quality,Screen Time Affects Sleep?
0,47,4,Yes,11,Yes,10,No,No,Bad,Yes
1,48,4,No,8,No,7,Yes,Yes,Bad,Yes
2,40,7,Sometimes,10,No,4,No,Yes,Bad,Yes
3,26,10,Yes,5,Yes,1,Yes,No,Good,No
4,47,5,Yes,7,Yes,7,Yes,No,Good,Yes
...,...,...,...,...,...,...,...,...,...,...
1181,21,10,สดชื่น,8,ใช่,4,ไม่หงุดหงิด/ไม่วิตกกังวล,ใช่,ดี,ไม่แน่ใจ
1182,17,7-8,ไม่สดชื่น,>8ชม.,ใช่,8,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ดี,ไม่แน่ใจ
1183,17,6-8,สดชื่น,3-4,ใช่,6,ไม่หงุดหงิด/ไม่วิตกกังวล,ใช่,ไม่ดี,ใช่
1184,17,6,ไม่สดชื่น,4,ใช่,6,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ไม่ดี,ใช่
1185,16,8,สดชื่น,8,ใช่,1,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ดี,ใช่

In [11]:
combined["Feel Rested"] = combined["Feel Rested"].replace("ไม่สดชื่น", "No").replace("สดชื่น", "Yes")
combined["Use Before Sleep"] = combined["Use Before Sleep"].replace("ไม่ใช้", "No").replace("ใช่", "Yes")
combined["Anxiety/Low Mood"] = combined["Anxiety/Low Mood"].replace("ไม่หงุดหงิด/ไม่วิตกกังวล", "No").replace("หงุดหงิด/วิตกกังวล", "Yes")
combined["Wellness Apps"] = combined["Wellness Apps"].replace("ไม่ใช่", "No").replace("ใช่", "Yes")
combined["Sleep Quality"] = combined["Sleep Quality"].replace("ไม่ดี", "Bad").replace("ดี", "Good")
combined["Screen Time Affects Sleep?"] = combined["Screen Time Affects Sleep?"].replace("ไม่แน่ใจ", "Not Sure").replace("ใช่", "Yes").replace("ไม่ใช่", "No")

In [12]:
combined

,Age,Sleep Hours,Feel Rested,Daily Screen Time,Use Before Sleep,Stress Level,Anxiety/Low Mood,Wellness Apps,Sleep Quality,Screen Time Affects Sleep?
0,47,4,Yes,11,Yes,10,No,No,Bad,Yes
1,48,4,No,8,No,7,Yes,Yes,Bad,Yes
2,40,7,Sometimes,10,No,4,No,Yes,Bad,Yes
3,26,10,Yes,5,Yes,1,Yes,No,Good,No
4,47,5,Yes,7,Yes,7,Yes,No,Good,Yes
...,...,...,...,...,...,...,...,...,...,...
1181,21,10,Yes,8,Yes,4,No,Yes,Good,Not Sure
1182,17,7-8,No,>8ชม.,Yes,8,No,No,Good,Not Sure
1183,17,6-8,Yes,3-4,Yes,6,No,Yes,Bad,Yes
1184,17,6,No,4,Yes,6,No,No,Bad,Yes
1185,16,8,Yes,8,Yes,1,No,No,Good,Yes